services:
  dag-scheduler-ui:
    build:
      context: .
    image: multi-cluster-dag-scheduler:local
    ports:
      - "8080:8080"
    environment:
      KUBECONFIG: /kube/config
    volumes:
      - ${USERPROFILE}/.kube:/kube:ro
    restart: unless-stopped
